BuildForSDG/team-132-backend

- .eslintrc.js
- __tests__/integration/farmer.register.test.js
- __tests__/testDb.test.js
- __tests__/unknownRoutes.test.js
- __tests__/utils.js
- api.rest
- jest.config.js
- package.json
- src/app.js
- src/config/dbConfig.js
- src/config/startServer.js
- src/controllers/farmer.controller.js
- src/models/User.js
- src/routes/farmer.router.js
- src/routes/index.js
- src/server.js
- src/services/farmer.service.js
- src/validator/farmer.validator.js
- yarn.lock
- Add yap validator
- Add model, controller, and service dir
- Set up router
- add error handler, used by calling next(error) in catch black
- add tests for register farmer
- add start and stop script for testdata
- add mongo-memory-server to use memory for tests
- add a test util file
1. Bcrypt
2. yup
3. mongodb-memory-server - in-memory database for testing
Fixes #(2) 
- In progress
Include details of your testing environment, and the tests you ran to see how your change affects other areas of the …
> Ft Create Farmer API

- yarn.lock
- Travis configuration.
Fixes #10
> Yarn changes

- .travis.yml
- __tests__/testData.test.js
- __tests__/utils.js
- jest.config.js
- package.json
- Added travis ci integration.
Fixes #10
> Added travis integration

- .travis.yml
- __tests__/testData.test.js
- app.properties
- Updated app.properties file with the project's required details.
> ch: updated app-properties file-16

- __tests__/testData.test.js
- app.properties
- Fixes app.properties to reflect real GitHub usernames.
> fx: fixes app.properties file github usernames

- src/controllers/farmer.controller.js
- src/middleware/access.js
- src/middleware/auth.js
- src/models/User.js
- src/routes/farmer.router.js
- src/validator/farmer.validator.js
Authenticate users based on their role in the system
The user role is passed in the user payload when logging in.
> feat:(role based access)

- src/controllers/adminController.js
- src/controllers/farmer.controller.js
- src/middleware/insuranceCompany.js
- src/models/insuranceCompany.js
- src/routes/admin.router.js
- src/routes/index.js
- src/services/admin.service.js
- src/validator/admin.validator.js
- src/validator/farmer.validator.js
- MongoDb
- Expressjs
- mongoose
Fixes #27 
- Tested all endpoint on this PR with the postman
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation
> Ft insurance crud

- src/controllers/farmer.controller.js
- src/routes/farmer.router.js
Allows admin to perform crud on farmers
MongoDb
Expressjs
mongoose
Nodejs
Fixes #26 
- All chnages has been tested on Postman
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation
> feat:(Farmers crud)

- src/controllers/adminController.js
- src/routes/admin.router.js
Admin can be able to manage all uploaded products by the farmers
MongoDb
Expressjs
mongoose
Nodejs
Fixes #25 
- All changes have been tested with postman.
- [ x] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline …
> feat:(manage uploaded products)

- src/controllers/adminController.js
- src/routes/admin.router.js
This PR allows admin to manage all agro-chemicals companies
MongoDb
Expressjs
mongoose
Nodejs
Fixes #28 
- The changes have been tested on Postman.
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have added necessary inline code …
> feat:(manage agro-chemicals companies)

- src/controllers/adminController.js
- src/middleware/admin.js
- src/routes/admin.router.js
- src/validator/isEmpty.js
This PR allows users to manage their acoount, where they can be able to update their details.
fixes #29
MongoDb
Expressjs
mongoose
Nodejs
Fixes #29 
- The changes have been tested on Postman.
- [x ] I have commented my code, particularly in hard-to-understand areas
- …
> feat:(manage user profile)

- src/controllers/farmInput.controller.js
- src/controllers/farmProduct.controller.js
- src/routes/farmer.router.js
A logged in buyer can be able to view all products available for purchase. 
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have added necessary inline code documentation
> A logged in user should be able to view all farm products available

- src/controllers/farmInput.controller.js
- src/routes/farmer.router.js
minor post and update farm input fixes
> post update fixes

- src/controllers/bestPractices.controller.js
- src/models/bestPractices.js
- src/routes/bestPractice.router.js
- src/services/farmingInformation.service.js
- src/validator/organicInformationValidator.js
This PR allows agrochemical companies to write about best practices in organic farming.
MongoDb
Expressjs
mongoose
Nodejs
yup
Fixes #49 
- All changes have been tested thoroughly on Postman client.
- [x ] I have commented my code, particularly in hard-to-understand …
> fx:(add farming information)

- package.json
- src/config/startServer.js
- yarn.lock
- changes to facilitate deployment.
> deployment preparation

- package.json
> specified node version in package.json file

- package.json
> new prod changes

- .gitignore
- package.json
> Fixed heroku errors

- .gitignore
- package.json
> Fixes heroku errors

- .eslintignore
- package.json
> Build changes

- .eslintignore
- .gitignore
- package.json
> Build new changes

- package.json
> fiexd start script

- .eslintignore
- package.json
> heroku fixes
